### ISSUE TITLE
sshkey file layout

### ISSUE THREAD

**Issue by HansH111** [mkj/dropbear#253]
Just a question;

I think the private key layout is something like
4 bytes =   length data
data  = type of key :  ssh-rsa or ecdsa-sha2-nistpXXX or ssh-ed25519
depending on type of key repeat until EOF
   4 bytes = length data
   data

Is this correct ?

I was just looking in the file layout and if I can make a sshkey recognizable that it is encrypted or not.
So you could do that by making an uppercase for the 1st letter of the type of a key and only encrypt the data parts of the file.

**Comment by mkj** [comment]
The private format is the specification's public key format, followed by the private key parameters. So for ed25519 as an example

https://github.com/mkj/dropbear/blob/master/src/ed25519.c#L78

From rfc0709  
```

   string  "ssh-ed25519"
   string  pubkey
   string privkey
```

I'd be inclined to OpenSSH  format for private keys, see https://github.com/mkj/dropbear/issues/209#issuecomment-1709254714

If extending Dropbear's format otherwise my inclination would be to add a fixed identifer at the start (and a version field!), then encrypt the current key as-is after that.
