### ISSUE TITLE
Can I Replace LibTomCrypt with OpenSSL?

### ISSUE THREAD

**Issue by isinglever** [mkj/dropbear#256]
Hi, I use deopbear as ssh server in my project. But I want to know can I easily replace libtomcrypt with OpenSSL in dropbear project? I’ve already compiled OpenSSL in my own project and don’t want to use an additional encryption library.
Thanks!

**Comment by mkj** [comment]
It would be possible but I don't know of anyone who's done it.

**Comment by isinglever** [comment]
> It would be possible but I don't know of anyone who's done it.

Thanks for your reply. I’ve reviewed some of the project’s code and found that the parts related to encryption are tightly coupled with libtomcrypt. It seems challenging to replace it with OpenSSL.

**Comment by stokito** [comment]
I also thought about this to make a smaller firmware for OpenWrt. But here it's even better that the DB uses own crypto library and not depends on others. A user may update the OpenSSL and broke an SSH access. We can probably link statically the OpenSSL but then it will give no any disk space saving so why to do that.

Potentially maybe it would be possible to make the libtomcrypt as a general TLS provider to use in OpenWrt instead of OpenSSL, mbedTLS, WolfSSL etc.
That's probably too big task with not that great benefits.
I also found an interesting TS library [BearSSL](https://bearssl.org/) that by a description sounds similar to the libtomcrypt.
